<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select Course--BYU In_1</name>
   <tag></tag>
   <elementGuidId>fded897f-f983-43f0-a151-71d8d733a2c8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control modalCourseId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>courseId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>courseId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select Course--BYU Indep Math 313 Elem Linear AlgBYU Math 110 Col. AlgBYU Math 112 CalculusBYU Math 119 Intro to CalculusBYU STAT 121 Principles of StatisticsMath 1030 Contemparory MathMath 1040 StatisticsMath 1050 College AlgebraMath 1060 TrigonometryMath 1070 Intro Stats InferenceMath 1100 Business CalculusMath 1210 Calculus 1Math 1220 Calculus 2Math 2210 Calculus 3STAT 121 Principles of StatisticsOther</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;courseId&quot;)</value>
   </webElementProperties>
</WebElementEntity>
