<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Chemistry</name>
   <tag></tag>
   <elementGuidId>daf88ac2-ec06-48fd-8a01-ee4176036f9b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chemistry</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;science&quot;)/div[5]/div[@class=&quot;panel panel-default panel-primary&quot;]/div[@class=&quot;panel-heading&quot;]/h3[@class=&quot;panel-title&quot;]/button[@class=&quot;btn btn-md btn-warning&quot;]/span[@class=&quot;text-3&quot;]</value>
   </webElementProperties>
</WebElementEntity>
