<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_agreeTerms</name>
   <tag></tag>
   <elementGuidId>769d3a4d-e706-4a76-bcff-fd57b9f61e71</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>agreeTerms</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reviewandSubmitForm&quot;)/div[@class=&quot;panel panel-default panel-primary&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/div[1]/input[@class=&quot;agreeTerms&quot;]</value>
   </webElementProperties>
</WebElementEntity>
